version: "2"
services:
  php:
    image: "php:8.0.0-fpm-buster"
    networks:
      - app-network
    volumes:
      - ./src:/var/www/html
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge